# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onproject', '0002_auto_20160822_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 8, 23, 15, 32, 34, 60677, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.CharField(max_length=20),
        ),
    ]
