# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onproject', '0003_auto_20160823_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 8, 23, 16, 22, 58, 649878, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
