# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onproject', '0004_auto_20160823_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment_id',
            field=models.IntegerField(),
        ),
    ]
